-- 코드를 작성해주세요
SELECT
    info.ITEM_ID,
    ITEM_NAME,
    RARITY
FROM ITEM_INFO info
JOIN ITEM_TREE tree ON info.ITEM_ID = tree.ITEM_ID
WHERE info.ITEM_ID NOT IN (
    SELECT DISTINCT PARENT_ITEM_ID
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NOT NULL
)
ORDER BY info.ITEM_ID desc