-- 코드를 입력하세요
SELECT
    c.CAR_ID,
    c.CAR_TYPE,
    FLOOR(c.DAILY_FEE * 30 * (100 - p.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
    ON c.CAR_TYPE = p.CAR_TYPE
    AND DURATION_TYPE = '30일 이상'
WHERE c.CAR_TYPE IN ('세단', 'SUV')
    AND NOT EXISTS (
        SELECT 
        *
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
        WHERE h.CAR_ID = c.CAR_ID
            AND h.START_DATE <= '2022-11-30'
            AND h.END_DATE >= '2022-11-01'
    )
    AND FLOOR(c.DAILY_FEE * 30 * (1 - p.DISCOUNT_RATE / 100)) BETWEEN 500000 AND 1999999
ORDER BY FEE desc, c.CAR_TYPE, c.CAR_ID desc









# SELECT
#     C.CAR_ID,
#     C.CAR_TYPE,
#     FLOOR(30 * C.DAILY_FEE * (100 - P.DISCOUNT_RATE) / 100) AS FEE
# FROM CAR_RENTAL_COMPANY_CAR C
# JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
#   ON P.CAR_TYPE = C.CAR_TYPE
#  AND P.DURATION_TYPE = '30일 이상'
# WHERE C.CAR_TYPE IN ('세단', 'SUV')
#   AND NOT EXISTS (
#         SELECT 1
#         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
#         WHERE H.CAR_ID = C.CAR_ID
#           AND H.START_DATE <= '2022-11-30'
#           AND H.END_DATE   >= '2022-11-01'
#       )
#   AND FLOOR(C.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE/100)) BETWEEN 500000 AND 1999999
# ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC