-- 코드를 입력하세요
SELECT
    YEAR(SALES_DATE) YEAR,
    MONTH(SALES_DATE) MONTH,
    GENDER,
    COUNT(DISTINCT u.USER_ID) USERS
FROM USER_INFO u 
JOIN ONLINE_SALE o ON u.USER_ID = o.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR, MONTH, GENDER