-- 코드를 입력하세요
SELECT
    fp.PRODUCT_ID,
    PRODUCT_NAME,
    SUM(PRICE * AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT fp
JOIN (
    SELECT *
    FROM FOOD_ORDER
    WHERE MONTH(PRODUCE_DATE) = 5
) fo ON fp.PRODUCt_ID = fo.PRODUCT_ID
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, fp.PRODUCT_ID