-- 코드를 입력하세요
SELECT
    fh.FLAVOR
FROM FIRST_HALF fh
JOIN (
    SELECT 
        SHIPMENT_ID,
        FLAVOR,
        SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) AS j ON fh.FLAVOR = j.FLAVOR
GROUP BY j.FLAVOR
ORDER BY fh.TOTAL_ORDER + j.TOTAL_ORDER desc
LIMIT 3

