SELECT gb.WRITER_ID, gu.NICKNAME, SUM(gb.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD gb
LEFT JOIN USED_GOODS_USER gu
    ON gb.WRITER_ID = gu.USER_ID
WHERE gb.STATUS = 'DONE'
GROUP BY gb.WRITER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES

