-- 코드를 입력하세요
SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) >= 9
    AND HOUR(DATETIME) < 20
GROUP BY HOUR(DATETIME)
# HAVING HOUR(DATETIME) BETWEEN 9 AND 19
ORDER BY HOUR(DATETIME)