-- 코드를 입력하세요
SELECT
    MEMBER_NAME,
    REVIEW_TEXT,
    DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW rr
JOIN MEMBER_PROFILE mp 
    ON rr.MEMBER_ID = mp.MEMBER_ID
WHERE rr.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
        SELECT MAX(CNT)
        FROM (
            SELECT MEMBER_ID, COUNT(*) AS CNT
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
        ) T
    )
)
ORDER BY REVIEW_DATE, REVIEW_TEXT