-- 코드를 작성해주세요
WITH SCORE_SUM AS (
    SELECT
        EMP_NO,
        SUM(SCORE) AS SUM_SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
)

SELECT
    SUM_SCORE AS SCORE,
    s.EMP_NO,
    EMP_NAME,
    POSITION,
    EMAIL
FROM SCORE_SUM s
JOIN HR_EMPLOYEES h ON s.EMP_NO = h.EMP_NO
ORDER BY SCORE desc
LIMIT 1