-- 코드를 작성해주세요
SELECT
    e.DEPT_ID,
    DEPT_NAME_EN,
    ROUND(SUM(SAL) / COUNT(EMP_NO), 0) AS AVG_SAL
FROM HR_EMPLOYEES e
JOIN HR_DEPARTMENT d ON e.DEPT_ID = d.DEPT_ID
GROUP BY e.DEPT_ID
ORDER BY AVG_SAL desc